export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// automatically created -> main layout of the application

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
